### 6. 예외

-예외는 정상적인 프로그램의 흐름을 방해하는 것으로, 항상 예측 불가능한 것은 아니다.

```javascript 1.8

/** throw 문은 함수의 실행을 중단단다.
*   throw 문은 어떠 예외인지 알 수 있게 해 주는 name 속성과 예외에 대해 설명하는 message 속성을 가진 예외 객체를 반환해야 한다. 
*   (필요한 속성이 더 있다면 추가할 수 있다.) */
var add = function(a, b) {
    if(typeof a !== 'number' || typeof b !== 'number'){
        throw {
            name: 'TypeError',
            message: 'add needs numbers'
        };
    }
    return a + b;
};

var try_it = function() {
    try{
        add("seven");
    } catch (e) {
        console.log(e.name + ': ' + e.message);
    }
};
    
try_it();
```

-try 블록에서 예외가 발생하면, 제어는 catch 블록으로 이동한다. 